// splashes.js
const splashTexts = [
  "Don't dig straight down!",
  "Watch out for Creepers!",
  "Now with emeralds!",
  "I.....AM STEVE!!!",
  "Craft, jump, repeat!",
  "Made with pixels and passion!",
  "Punch trees to begin!",
  "More TNT, more fun!",
  "MC Run is fun!",
  "Creepers gonna creep!",
  "Steve approves!",
  "Made by GamerArnabXYZ!",
  "Blocks are life!",
  "Can you beat your high score?",
  "Slimes love hugs!",
  "Build your destiny!",
  "100% less bugs*",
  "*maybe",
  "Mining all day!",
  "Jump like a pro!",
  "Double tap to survive!",
  "Eat, sleep, mine, repeat!",
  "Parkour time!",
  "Zombies hate sunlight!",
  "Cows go moo!",
  "Epic runs await!",
  "Retro pixels FTW!",
  "Feeling blocky today?",
  "Break blocks, not hearts!",
  "More emeralds, more skins!",
  "Steve never sleeps!",
  "Powered by redstone!",
  "The floor is lava!",
  "Are you ready to run?",
  "No Herobrine, we promise!",
  "One jump to rule them all!",
  "Explosions included!",
  "Try not to blow up!",
  "Even villagers play it!",
  "Jump like an Enderman!",
  "Sleep in a bed to set spawn!",
  "Always carry a pickaxe!",
  "This is not a drill!",
  "Unleash your inner builder!",
  "Sun is up, run begins!",
  "Zombies at night!",
  "Ready, set, explode!",
  "Don’t feed the TNT!",
  "Blocks and beats!",
  "Swipe to glory!",
  "Tap tap tap!"
];
